//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Database.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public double Price { get; set; }
        public double Tax { get; set; }
        public double Discount { get; set; }
        public Nullable<System.DateTime> PromotionStartDate { get; set; }
        public Nullable<System.DateTime> PromotionEndDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public int DepartmentId { get; set; }
        public bool IsRawMaterial { get; set; }
        public Nullable<int> ItemGroupId { get; set; }
        public string Remarks { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Department Department { get; set; }
        public virtual ItemGroup ItemGroup { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
