//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Database.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobCardHead
    {
        public int Id { get; set; }
        public string JobNo { get; set; }
        public Nullable<System.DateTime> JobData { get; set; }
        public string CarRegistrationNo { get; set; }
        public string ModelYear { get; set; }
        public string Milleage { get; set; }
        public Nullable<System.DateTime> DataTimeIn { get; set; }
        public string CarMake { get; set; }
        public string CarModel { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CustomerContactNo { get; set; }
        public string EngineNo { get; set; }
        public string VINno { get; set; }
        public string Patrol { get; set; }
        public string Reporteddefect { get; set; }
        public string CompleteActione { get; set; }
        public string VehicleBodyReportComents { get; set; }
        public Nullable<int> ODoMeter { get; set; }
        public Nullable<int> Hours { get; set; }
        public Nullable<int> NextService_Miles { get; set; }
        public int VendorId { get; set; }
        public string DocNo { get; set; }
        public string Remarks { get; set; }
        public double Discount { get; set; }
        public double SurCharge { get; set; }
        public double GstCharges { get; set; }
        public double GrossAmount { get; set; }
        public double TotalNetAmount { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual Vendor Vendor { get; set; }
    }
}
