//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Database.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpeningHead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OpeningHead()
        {
            this.OpeningDetails = new HashSet<OpeningDetail>();
        }
    
        public int Id { get; set; }
        public string DocNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> SurCharge { get; set; }
        public Nullable<double> GstCharges { get; set; }
        public Nullable<double> GrossAmount { get; set; }
        public Nullable<double> TotalNetAmount { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpeningDetail> OpeningDetails { get; set; }
    }
}
