//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Database.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderFeedback
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> FoodExcellence { get; set; }
        public Nullable<int> ServiceLevel { get; set; }
        public Nullable<int> AmbienceTheme { get; set; }
        public Nullable<int> SelectionOfMusic { get; set; }
        public Nullable<int> OverallExperience { get; set; }
        public string Comments { get; set; }
        public string GuestName { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public bool IsEmailMarketing { get; set; }
        public bool IsSmsMarketing { get; set; }
        public bool IsWhatsAppMarketing { get; set; }
        public bool IsPhoneMarketing { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
