//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Database.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string ItemName { get; set; }
        public double Quantity { get; set; }
        public double Price { get; set; }
        public double TotalPrice { get; set; }
        public double TaxAmount { get; set; }
        public double Discount { get; set; }
        public Nullable<int> TableId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string Remarks { get; set; }
        public bool IsVoid { get; set; }
        public bool IsComplimentary { get; set; }
        public string Reason { get; set; }
        public Nullable<int> DepartmentId { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
