//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Database.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderFeedbacks = new HashSet<OrderFeedback>();
            this.OrderItems = new HashSet<OrderItem>();
            this.OrderTableHistories = new HashSet<OrderTableHistory>();
        }
    
        public int Id { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public double GSTPerentage { get; set; }
        public double FOCDiscount { get; set; }
        public double DiscountPercentage { get; set; }
        public double BankDiscount { get; set; }
        public double DiscountVoucher { get; set; }
        public double Tip { get; set; }
        public double ServiceChargesPerentage { get; set; }
        public double GstCharged { get; set; }
        public double DiscountCharged { get; set; }
        public double ServiceCharged { get; set; }
        public double GrossAmount { get; set; }
        public double TotalNetAmount { get; set; }
        public double ReceiptTotalCash { get; set; }
        public double ReceiptTotalCredit { get; set; }
        public double Change { get; set; }
        public Nullable<int> TableId { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public bool IsUpdateMode { get; set; }
        public bool IsPayment { get; set; }
        public Nullable<System.DateTime> ShopOpenOrderDate { get; set; }
        public Nullable<int> OrderTypeId { get; set; }
        public Nullable<int> NoOfGuest { get; set; }
        public bool IsVoid { get; set; }
        public bool IsComplimentary { get; set; }
        public string Reason { get; set; }
        public Nullable<double> AlignmentAmount { get; set; }
        public Nullable<double> wheelBalanceAmount { get; set; }
        public Nullable<double> NitrogenGas { get; set; }
        public Nullable<double> TPMS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderFeedback> OrderFeedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual OrderType OrderType { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderTableHistory> OrderTableHistories { get; set; }
    }
}
