//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Database.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationHead
    {
        public int Id { get; set; }
        public int VendorId { get; set; }
        public Nullable<int> Pono { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<System.DateTime> QuotationDate { get; set; }
        public Nullable<System.DateTime> DateOFSupplyDate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<System.DateTime> VoildUptoDate { get; set; }
        public string DocNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> SurCharge { get; set; }
        public Nullable<double> GstCharges { get; set; }
        public Nullable<double> GrossAmount { get; set; }
        public Nullable<double> TotalNetAmount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> WarehousesID { get; set; }
        public Nullable<int> ReceivedID { get; set; }
        public Nullable<System.DateTime> ArrivalTime { get; set; }
        public Nullable<System.DateTime> UnloadedTime { get; set; }
        public string VehicleNo { get; set; }
        public string TransportCompany { get; set; }
        public Nullable<double> TransportionCost { get; set; }
    
        public virtual Vendor Vendor { get; set; }
        public virtual Vendor Vendor1 { get; set; }
    }
}
