//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Database.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnToVendorHead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReturnToVendorHead()
        {
            this.ReturnToVendorDetails = new HashSet<ReturnToVendorDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string DocNo { get; set; }
        public string Remarks { get; set; }
        public int LocationId { get; set; }
        public int DepartmentId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public double Discount { get; set; }
        public double SurCharge { get; set; }
        public double GstCharges { get; set; }
        public double GrossAmount { get; set; }
        public double TotalNetAmount { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnToVendorDetail> ReturnToVendorDetails { get; set; }
    }
}
