//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Database.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopStatus
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateOpen { get; set; }
        public Nullable<bool> OpenStatus { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public Nullable<bool> ClosedStatus { get; set; }
        public Nullable<int> ShopOpenUserId { get; set; }
        public Nullable<int> ShopCloseUserId { get; set; }
    }
}
