//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Database.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRight
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int MenuId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual MainMenu MainMenu { get; set; }
        public virtual User User { get; set; }
    }
}
